name: Build and test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build and test'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          bundler-cache: true

      - name: Build
        run: bundle exec middleman build

      - name: Check for broken links
        run: bundle exec rake check_urls
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
